# Generated by Django 4.1.4 on 2022-12-22 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dist1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dist1',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dist1',
            name='done',
            field=models.CharField(choices=[('doing', 'fazendo'), ('done', 'done')], max_length=5),
        ),
    ]
